### PR TITLE
Organise workspace crates and consolidate Cargo.toml manifest properties/dependencies

### PR DESCRIPTION
**Pull request by Swoorup**
Simplify hacking on this repo by 
* Allowing to change the version from a single Cargo.toml instead of multiple crates.
* Single place to update external dependency version instead of multiple cargo.toml's

### CODE REVIEW

**Comment by Maxxen** [comment]
This is def. a good idea, I'll pick this up and solve the conflicts after next release

**Comment by Swoorup** [comment]
Sure, I based few more changes, that fixes quite a far bit of the issues with appender (including adding support of union types and works well with nested types) atop this branch. Would be great to have it in.  Let me know if anything is needed. 

😃

**Comment by Maxxen** [comment]
Well, I am stumped, no clue why there's a bunch of leaks detected by ASAN now.

**Comment by Maxxen** [comment]
Ok think I fixed it

**Comment by Swoorup** [comment]
Anything preventing this merge btw?

**Comment by Maxxen** [comment]
Something silly with the last step of the CI. Working on it.

**Pull request merged**
